import Head from 'next/head'
import '../styles/globals.css'
import { ThemeProvider } from 'next-themes'
import { useEffect, useState } from 'react'

export default function App({ Component, pageProps }) {
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) return null

  return (
    <ThemeProvider enableSystem={true} attribute='class'>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/google_icon.png' />
      </Head>

      <Component {...pageProps} />
    </ThemeProvider>
  )
}
